version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
    environment:
      - MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - restore_cache:
          key: flaggy-build-{{ checksum "mix.lock" }}-v1
      - run: mix compile --warnings-as-errors --force
      - save_cache:
          key: flaggy-build-{{ checksum "mix.lock" }}-v1
          paths:
            - ~/repo/_build
      - run: mix test
      - run: mix credo
      - run: mix coveralls.html
      - store_test_results:
          path: /tmp/flaggy-test-results
      - store_artifacts:
          path: ~/repo/cover
          destination: coverage

