version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
    steps:
      - checkout
      - run: export MIX_ENV=test
      - run: mix deps.get
      - run: mix test
      - run: mix credo
      - run: mix coveralls
